version: "3"

services:
  frontend:
    build: ./frontendapp
    ports:
      - "3000:3000"
    networks:
      - mern

  backend:
    build: ./backendapp
    ports:
      - "2032:2032"
    networks:
      - mern

  nagios:
    image: jasonrivers/nagios
    container_name: nagios
    ports:
      - "8081:80"
    environment:
      - NAGIOS_FQDN=nagios.local
    volumes:
      - ./nagios/mern.cfg:/opt/nagios/etc/servers/mern.cfg
    networks:
      - mern

networks:
  mern:
    driver: bridge
